name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -out=tfplan.binary
        echo "exitcode=$?" >> $GITHUB_OUTPUT

    - name: Terraform Apply
      if: steps.plan.outputs.exitcode == '2'
      run: terraform apply -auto-approve tfplan.binary
